### ISSUE TITLE
x86 version of Windows

### ISSUE THREAD

**Issue by BhasitL** [LemonPi314/dvd-screensaver#1]
This is compatible with only x64 bit Windows. Is it possible to have a 32 bit version? Please

**Comment by LemonPi314** [comment]
A workflow for x86 builds has been added. Let me know if it works.

**Comment by BhasitL** [comment]
Hi LemonPi344,                            Thank you for taking my request into consideration by creating a x86 version of the screensaver. Unfortunately, I have copied it to the System32 folder where default screensavers are found but it gives me an error message when trying to launch it. Please find attached a snip of the error message. Thanks,BhasitLFrom: LemonPi314Sent: Sunday, 13 March 2022 23:06To: LemonPi314/dvd-screensaverCc: BhasitL; AuthorSubject: Re: [LemonPi314/dvd-screensaver] x86 version of Windows (Issue #1) A workflow for x86 builds has been added. Let me know if it works.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***> 

	
        
		Virus-free. www.avast.com

**Comment by LemonPi314** [comment]
I cannot see your attachment, try sending it using the GitHub web interface instead of email.

**Comment by BhasitL** [comment]
Hi, Sorry for the late reply. Actually I had forgotten to attach the snip. I will attach it in this mail. The error message says that “Cannot open PyInstaller archive from executable (C:\Windows\System32\dvd-screensaver-x86.scr) or external archive (C:\Windows\System32\dvd-screensaver-x86.pkg)”Thanks From: LemonPi314Sent: Monday, 14 March 2022 00:59To: LemonPi314/dvd-screensaverCc: BhasitL; AuthorSubject: Re: [LemonPi314/dvd-screensaver] x86 version of Windows (Issue #1) I cannot see your attachment, try sending it using the GitHub web interface instead of email.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***> 

	
        
		Virus-free. www.avast.com

**Comment by BhasitL** [comment]
I saw that the attachment still does not appear in GitHub web interface and so I am attaching it here
![Capture](https://user-images.githubusercontent.com/101442924/158116042-a89c0cb6-11e8-4cb9-a6ea-feec4160dc91.PNG)
.

**Comment by LemonPi314** [comment]
It seems that x86 Pyinstaller packages have issues running from the System32 folder. Try moving the screensaver file to a user folder like `%APPDATA%/LemonPi314/dvd-screensaver` (same folder as the screensaver's `config.json`). Then right click on it and select "Install".

**Comment by BhasitL** [comment]
Ok. Thank you for your time ☺️
